# Python Basic Exercises

1) Create a function that acts as a simple calculator with operations addition, subtraction, multiplication and division.

If the operation is not specified, default to multiplication. If the operation is misspecified, return an error message.
        
        Ex: 
calculator(3,5,"multiply") returns 15 

calculator(3,5) returns 15  

calculator(3, 5, "something") returns error message.







In [47]:
def calc(num1,num2,string = 'multiplication'):
    if string == 'addition':
        return num1+num2
    if string == 'subtraction':
        return num1-num2
    if string == 'division':
        return num1/num2
    if string == 'multiplication':
        return num1*num2
    else:
        return "invalid"

In [51]:
calc(3,5, 'divisio')

'invalid'

2) a) Given a list of numbers, return a list where all adjacent duplicate elements have been removed.

Ex:

[2, 2, 2, 3, 2] returns [ 2, 3, 2]. 

In [58]:
def duplicate(arr):
    prev = [arr[0]]
    for i in range(len(arr)-1):
        if arr[i+1] != arr[i]:
            prev.append(arr[i+1])
    return prev

In [59]:
array = [2,2,2,3,2]
duplicate(array)

[2, 3, 2]

b) Remove all duplicate values (adjacent or not)

Ex:

[1, 2, 2, 3, 2,3,1] returns [1, 2, 3] 

In [89]:
def dupli(arr):
    prev = []
    i = 0
    while i < len(arr):
        if (arr[i] not in prev):
            prev.append(arr[i])
        i+=1
    return prev

In [92]:
arr =[1, 2, 2, 3, 2,3,1,4,5,5,6,10,10,9]
dupli(arr)

[1, 2, 3, 4, 5, 6, 10, 9]

3) Given the array:  X= np.random.randn(3,5)   \# creates random normals in 3x5 array

For each column find the row index of the maximum value using loop.


In [6]:
import numpy as np
X = np.random.randn(3,5)

In [44]:
def maxrowindex(arr): 
      
    # get number of rows and columns 
    no_of_rows, no_of_columns = arr.shape
#     no_of_rows = len(arr) 
#     no_of_column = len(arr[0]) 
    for j in range(no_of_column):
        max1 = -1000
        for i in range(no_of_rows): 
             if arr[i][j] > max1 : 
                    max1 = arr[i][j] 
        print(np.where(arr == max1))

In [45]:
maxrowindex(X)

(array([0], dtype=int64), array([0], dtype=int64))
(array([1], dtype=int64), array([1], dtype=int64))
(array([2], dtype=int64), array([2], dtype=int64))
(array([0], dtype=int64), array([3], dtype=int64))
(array([0], dtype=int64), array([4], dtype=int64))


In [46]:
X


array([[ 1.51024592,  0.47691392, -1.09468683,  0.55548431,  1.49053684],
       [-0.48397111,  1.16100117, -1.23906854, -0.73726407, -0.61319215],
       [-0.03522472, -0.85145015, -0.85038795, -0.40858181, -0.04872963]])

4) Get csv from the following link,
https://raw.github.com/neurospin/pystatsml/master/datasets/salary_table.csv

Create table from the csv file.

Check for missing data and remove those entries from the table.

In [2]:
import pandas as pd
df  = pd.read_csv("salary_table.csv")

In [98]:
df = df.replace('N', np.NaN)

In [99]:
df.dropna()

salary  experience education management
0    13876           1  Bachelor          Y
2    18701           1      Ph.D          Y
5    20872           2    Master          Y
10   14975           3  Bachelor          Y
11   21371           3    Master          Y
12   19800           3      Ph.D          Y
14   20263           4      Ph.D          Y
19   15965           5  Bachelor          Y
21   21352           6      Ph.D          Y
24   16978           7  Bachelor          Y
26   17404           8  Bachelor          Y
27   22184           8      Ph.D          Y
31   23174          10      Ph.D          Y
32   23780          10    Master          Y
33   25410          11    Master          Y
36   24170          12      Ph.D          Y
38   26330          13    Master          Y
40   25685          15      Ph.D          Y
41   27837          16    Master          Y

6) Use the file data.txt. Read, the file and count the occurrences of each word within the file. Store the words’ occurrence number in a dictionary. 

In [77]:
with open ("text.txt.txt", "r") as myfile:
    data=myfile.readlines()

In [78]:
data

["Data analysis is a process of inspecting, cleansing, transforming and modeling data with the goal of discovering useful information, informing conclusions and supporting decision-making. Data analysis has multiple facets and approaches, encompassing diverse techniques under a variety of names, and is used in different business, science, and social science domains. In today's business world, data analysis plays a role in making decisions more scientific and helping businesses operate more effectively."]

In [86]:
def word_count(str):
    counts = dict()
    words = str.split()

    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1

    return counts
string  = data[0]

In [87]:
word_count(string)

{'Data': 2,
 'analysis': 3,
 'is': 2,
 'a': 3,
 'process': 1,
 'of': 3,
 'inspecting,': 1,
 'cleansing,': 1,
 'transforming': 1,
 'and': 6,
 'modeling': 1,
 'data': 2,
 'with': 1,
 'the': 1,
 'goal': 1,
 'discovering': 1,
 'useful': 1,
 'information,': 1,
 'informing': 1,
 'conclusions': 1,
 'supporting': 1,
 'decision-making.': 1,
 'has': 1,
 'multiple': 1,
 'facets': 1,
 'approaches,': 1,
 'encompassing': 1,
 'diverse': 1,
 'techniques': 1,
 'under': 1,
 'variety': 1,
 'names,': 1,
 'used': 1,
 'in': 2,
 'different': 1,
 'business,': 1,
 'science,': 1,
 'social': 1,
 'science': 1,
 'domains.': 1,
 'In': 1,
 "today's": 1,
 'business': 1,
 'world,': 1,
 'plays': 1,
 'role': 1,
 'making': 1,
 'decisions': 1,
 'more': 2,
 'scientific': 1,
 'helping': 1,
 'businesses': 1,
 'operate': 1,
 'effectively.': 1}